version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: marketplace
          POSTGRES_DB: marketplace
    working_directory: /tmp/marketplace
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: sudo apt-get update && sudo apt install -y libusb-1.0-0 libusb-1.0-0-dev
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: 
          name: (backend) Install packages
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: (backend) Build
          command: npm run build:ci
          environment:
            CONNECTION_STRING: 'postgres://marketplace@localhost:5432/marketplace'
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "webapp/package.json" }}
          - v1-dependencies-
      - run: 
          name: (frontend) Install packages
          command: cd webapp && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "webapp/package.json" }}
      - run:
          name: (frontend) Build
          command: cd webapp && npm run build
          environment:
            NODE_PATH: src/
            REACT_APP_VERSION: 0.1
            REACT_APP_ROLLBAR_ACCESS_TOKEN: ad890a7699424114a771373ee60720ac
            REACT_APP_INTERCOM_APP_ID: z0h94kay
            REACT_APP_SEGMENT_API_KEY: tSPRGKC4F9cqdf1VbPwH5ToqNyNXSn5d
      - save_cache:
          paths:
            - webapp/build
          key: build-{{ .Branch }}-{{ .Revision }}
  deploy:
    docker:
      - image: circleci/node:9.11.1
    working_directory: /tmp/marketplace
    steps:
      - restore_cache:
          keys:
          - build-{{ .Branch }}-{{ .Revision }}
      - run: 
          name: Install system dependencies
          command: sudo apt-get -y -qq install python-setuptools python-dev build-essential && sudo easy_install pip && pip install awscli --upgrade --user
      - run:
          name: Remove old assets => S3
          command: ~/.local/bin/aws s3 rm ${APP_S3_BUCKET}static/ --recursive
      - run:
          name: Upload new assets => S3
          command: ~/.local/bin/aws s3 cp webapp/build ${APP_S3_BUCKET} --acl public-read --recursive
      - run:
          name: Invalidate Cloudfront cache
          command: ~/.local/bin/aws configure set preview.cloudfront true && ~/.local/bin/aws cloudfront create-invalidation --distribution-id ${APP_CF_DISTRIBUTION} --paths "/" "/*"

workflows:
  version: 2
  build-deploy-release:
    jobs:
      - build:
          context: marketplace-prd
          filters:
            branches:
              only: release
      - deploy:
          context: marketplace-prd
          requires:
            - build
  build-deploy-staging:
    jobs:
      - build:
          context: marketplace-stg
          filters:
            branches:
              only: staging
      - deploy:
          context: marketplace-stg
          requires:
            - build
  build-deploy-master:
    jobs:
      - build:
          context: marketplace-dev
          filters:
            branches:
              only: master
      - deploy:
          context: marketplace-dev
          requires:
            - build
  build-branch:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - release
                - staging
